name: Test application

on:
    pull_request:
    push:
        branches:
            - master
            - develop
            - '[0-9]+.[0-9]+'

jobs:
    test:
        name: "Run tests with php ${{ matrix.php-version }}"
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: mysql://root:root@127.0.0.1:3306/su_theme_test?serverVersion=5.7
            DATABASE_CHARSET: utf8mb4
            DATABASE_COLLATE: utf8mb4_unicode_ci

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.3'
                      database: mysql
                      phpcr-transport: doctrinedbal
                      composer-flags: '--prefer-lowest --prefer-stable --prefer-dist --no-interaction'
                      tools: 'composer:v1'
                      lint: false
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: disabled

                    - php-version: '7.4'
                      database: mysql
                      phpcr-transport: doctrinedbal
                      composer-flags: '--prefer-dist --no-interaction'
                      tools: 'composer:v2'
                      lint: true
                      php-extensions: 'imagick'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: disabled

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: ${{ matrix.php-extensions }}
                  tools: ${{ matrix.tools }}

            - name: Get composer cache directory
              id: composer-cache-dir
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              id: composer-cache
              with:
                  path: ${{ steps.composer-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                  composer validate
                  composer update ${{ matrix.composer-flags }}

            - name: Lint
              if: ${{ matrix.lint }}
              run: |
                  Tests/Application/bin/adminconsole cache:clear --env dev
                  Tests/Application/bin/websiteconsole cache:clear --env dev
                  composer lint
              env: ${{ matrix.env }}

            - name: Run tests
              run: composer test
              env: ${{ matrix.env }}

